# Generated by Django 4.2.3 on 2023-08-30 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_prudcut_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prudcut',
            new_name='Prudcuct',
        ),
    ]
