# Generated by Django 4.2.3 on 2023-08-30 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_prudcut_prudcuct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prudcuct',
            new_name='Product',
        ),
    ]
